# Application
spring.application.name=api

# 배포시에는 Postgres 사용
spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# SSL 설정 (NEON DB)
spring.datasource.hikari.jdbc-url=${DB_URL}

# 포트 설정
server.port=10000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI 경로
# OpenApi 문서 활성화화
springdoc.api-docs.enabled=true
#ui 활성화
springdoc.swagger-ui.enabled=true
# 기본 접속 경로 지정
springdoc.swagger-ui.path=/swagger-ui.html
#일반화된 응답 사용 여부 결정
springdoc.override-with-generic-response=false
# 배포 - render을 위한 swagger 고정
springdoc.server-url=https://voltupbe.onrender.com
